### PR TITLE
Net 4 compatibility

### LINKED ISSUE #7: .NET v4.0 compatibility
Hello Martin,

In version 3 of Dynamo you switched from .NET v4.0 to v4.5 as your target framework. My current codebase is running on v4.0.

When I upgraded to 3.0.0.1 I got the following error:
`Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.`

This error is caused by the fact that the ExtensionAttribute is moved from the System.Core to mscorlib assembly. See [http://stackoverflow.com/a/11265032](http://stackoverflow.com/a/11265032).

I have forked this project and changed the target framework back to v4.0, compiled it and include that assembly in my project, which fixed the problem for me.

So I was wondering if you plan to use v4.5 specific APIs? If not, we could add new projects targeting the v4.0 specifically. Via NuGet we can distribute runtime specific versions, see [http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-package#Framework_Names](http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-package#Framework_Names).

Regards,
Bert

### PR DESCRIPTION
**Pull request by devatwork**
Hello Martin,

This pull-request closes #7 .NET v4.0 compatibility.

I have made the following changes:
1. Created new cprojs targeting the v4.0 framework. The new cprojs only linked files. So any changes made in the v4.5 cprojs will automatically be made in v4.0 as well. Deleting an existing or adding a new file will require you to change the corresponding cproj as well. See [http://blogs.msdn.com/b/jjameson/archive/2009/04/02/linked-files-in-visual-studio-solutions.aspx](http://blogs.msdn.com/b/jjameson/archive/2009/04/02/linked-files-in-visual-studio-solutions.aspx) for more info about linked files.
2. Changed the output path of all the cprojs to bin\ in both debug and release mode. In this way it is easier to package them.
3. Extracted the nuspec files from your existing packages and modified them to support multiple framework versions.
4. Added a package command script to easily build the project in release mode and create the nuget packages.

I ran all the test against v4.0 and they all passed.

What needs to be done is:
1. Test if the build process works on v4.5. The msbuild path located at line 3 in package.cmd might need to be changed.
2. Publish a new version of these packages.

Please let me know if you run into problems with these changes or if you have questions.

Regards,
Bert

### CODE REVIEW

**Comment by MartinF** [comment]
Thanks - Great work :)

Sorry for the late answer, but I have just been on a vacation.

What is the reason why you want both Debug and Release configurations to go in the same bin\ directory? 
Why not keep them separated (release\ and debug) which is the default?

**Comment by devatwork** [comment]
Thanks, glad I can do something in return.

Not enough coffee I guess, I will update the pull request tomorrow.

**Comment by devatwork** [comment]
Hi Martin,

I have changed the output path back to bin\Debug or  bin\Release depending on the build config.

I also removed the hard-coded msbuild path from the package script. You can execute the package script within the Visual Studio Command  Prompt.

Let me know if you run into problems.

Regards,
Bert

**Comment by MartinF** [comment]
Perfect! Thanks :)

**Pull request merged**
